feat: change webapp service stack to php

diff --git a/webapp-service/docker/Dockerfile b/webapp-service/docker/Dockerfile
--- a/webapp-service/docker/Dockerfile
+++ b/webapp-service/docker/Dockerfile
@@ -1,12 +1,70 @@
-FROM golang:1.18
+ARG ALPINE_VERSION=3.19
+FROM alpine:${ALPINE_VERSION}
 
-# Application location on container
-WORKDIR /go/src/fiber
+LABEL Maintainer="Tim de Pater <code@trafex.nl>"
+LABEL Description="Lightweight container with Nginx 1.24 & PHP 8.3 based on Alpine Linux."
 
-# Dependency from host machine - Depends on "docker-compose.yml->build->context" path directory
-COPY . .
+# Setup document root
+WORKDIR /var/www/html
 
-# Once container built compile the program from host - Depends on "docker-compose.yml->build->context" path directory
-RUN go build -o bin/server app/main.go
+# Install packages and remove default server definition
+RUN apk add --no-cache \
+  curl \
+  nginx \
+  supervisor \
+  ## PHP
+  php83 \
+  php83-ctype \
+  php83-curl \
+  php83-dom \
+  php83-fileinfo \
+  php83-fpm \
+  php83-gd \
+  php83-intl \
+  php83-mbstring \
+  php83-opcache \
+  php83-openssl \
+  php83-phar \
+  php83-session \
+  php83-tokenizer \
+  php83-xml \
+  php83-xmlreader \
+  php83-xmlwriter \
+  ## database ext
+  #php83-mysqli \
+  php83-redis
 
-CMD ["./bin/server"]
+# Configure nginx - http
+COPY config/nginx.conf /etc/nginx/nginx.conf
+
+# Configure nginx - default server
+COPY config/conf.d /etc/nginx/conf.d/
+
+# Configure PHP-FPM
+ENV PHP_INI_DIR /etc/php83
+COPY config/fpm-pool.conf ${PHP_INI_DIR}/php-fpm.d/www.conf
+COPY config/php.ini ${PHP_INI_DIR}/conf.d/custom.ini
+
+# Configure supervisord
+COPY config/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
+
+# Make sure files/folders needed by the processes are accessable when they run under the nobody user
+RUN chown -R nobody.nobody /var/www/html /run /var/lib/nginx /var/log/nginx
+
+# Create symlink for php
+RUN ln -s /usr/bin/php83 /usr/bin/php
+
+# Switch to use a non-root user from here on
+USER nobody
+
+# Add application
+COPY --chown=nobody ../ /var/www/html/
+
+# Expose the port nginx is reachable on
+EXPOSE 80
+
+# Let supervisord start nginx & php-fpm
+CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
+
+# Configure a healthcheck to validate that everything is up&running
+#HEALTHCHECK --timeout=10s CMD curl --silent --fail http://127.0.0.1:8080/fpm-ping || exit 1
